<?php

/**
 * @var \Tresdadv\MiPrimerCrud\Block\Display $block
 */
 $Collection = $block->getPostCollection();
?>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<?php if($Collection): ?>
  <table>
    <tr>
      <th class="post-id">Id</th>
      <th class="post-fisrtname">Primer Nombre</th>
      <th class="post-lastname">Segundo Nombre</th>
      <th class="post-email">Correo</th>
      <th class="post-telephone">Telefono</th>
    </tr>
      <?php
          foreach ($Collection as $key=>$post){
              echo '<tr>
                      <td>'.$post->getId().'</td>
                      <td>'.$post->getFisrtName().'</td>
                      <td>'.$post->getLastName().'</td>
                      <td>'.$post->getEmail().'</td>
                      <td>'.$post->getTelephone().'</td>
                    </tr>';
          }
      ?>
  </table>
<?php  else: ?>
  <h1>NO existen registros</h1>
<?php endif; ?>
</body>

</html>